### ISSUE TITLE
getWalletTransaction gagal

### ISSUE THREAD

**Issue by febriankrisna** [anysz/ovopy#1]
Responnya begini mas
`error.OVOUnexpectedError: OVOHttpResponse(code=None, status=404, message='Data Not Found!', content=None, data=None, httpStatus=404)`
Barangkali sudah ganti url api nya ya?
Mohon bantuannya kalau ada update lagi.
Terimakasih banyak.

**Comment by ii64** [comment]
Is your issue already fixed?

**Comment by febriankrisna** [comment]
Yes, it's already fixed. The error occured when there is no transaction history. Somehow, OVO deleted them if older than 30 days, which is weird. Thank you for this amazing repo.
